@REM Run the model_trainer_subsets.py script for different fractions of the comparison data

@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.1
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.15
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.2
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.25
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.3
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.35
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.4
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.45
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.5
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.55
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.6
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.65
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.7
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.75
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.8
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.85
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.9
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.95
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic covid --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 1.0

@REM Run the model_trainer_subsets.py script for different fractions of the Anti-Vax data

"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.001
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.002
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.003
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.004
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.005
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.0075
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.01
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.025
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.05
"C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.075
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.1
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.15
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.2
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.25
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.3
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.35
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.4
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.45
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.5
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.55
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.6
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.65
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.7
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.75
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.8
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.85
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.9
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 0.95
@REM "C:\Users\jhont\miniconda3\envs\ml\python.exe" "C:\Users\jhont\OneDrive\Documents\Research\EAGER-Misinfo-NLP\model_trainer_subsets.py"  --topic 15k --tokenizer distilbert-base-uncased --model distilbert-base-uncased --epochs 21 --gpu False  --frac_train 1.0